double UNIVERSE_WIDTH = 800e9;
double UNIVERSE_HEIGHT = 600e9;
unsigned int TEXT_WIDTH = 80;
unsigned int TEXT_HEIGHT = 30;
double WIDTH_PRINT_RATIO = (double) (UNIVERSE_WIDTH / TEXT_WIDTH);
double HEIGHT_PRINT_RATIO = (double) (UNIVERSE_HEIGHT / TEXT_HEIGHT);
char PLANET_CHARACTER = '0';
// double SECONDS_BETWEEN_CALC = 2.59e6;
double SECONDS_BETWEEN_CALC = 604800;
unsigned int MICROSECONDS_BETWEEN_PRINT =20000;
double G = 6.67430e-11;

